name: TechTrends - Package with Docker

#trigger the workflow on push.
on:
  push:
    branches: [main]

jobs:
  build:
    #running the action on ubuntu latest operating system
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dockerchirulaptop
          password: Span@1234
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: dockerchirulaptop/techtrends:latest



